mod archive;
mod live;
mod none;

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct SlackWorkspaceApiCapabilities {
    pub subscribe_realtime: bool,
    pub load_shell: bool,
    pub load_sidebar: bool,
    pub load_dm_inbox: bool,
    pub load_all_threads: bool,
    pub load_activity: bool,
    pub mark_activity_item_read: bool,
    pub mark_activity_item_unread: bool,
    pub archive_activity_item: bool,
    pub unarchive_activity_item: bool,
    pub load_later: bool,
    pub mutate_later_reminders: bool,
    pub load_files: bool,
    pub load_file_metadata: bool,
    pub load_conversation_files: bool,
    pub load_canvas: bool,
    pub load_drafts_sent: bool,
    pub load_pins: bool,
    pub load_bookmark_folder: bool,
    pub load_conversation_members: bool,
    pub load_channel_details: bool,
    pub load_channel_notification_preferences: bool,
    pub mutate_channel_notification_preferences: bool,
    pub load_preferred_skin_tone: bool,
    pub mutate_preferred_skin_tone: bool,
    pub load_destination_directory: bool,
    pub load_reaction_catalog: bool,
    pub open_conversation: bool,
    pub load_conversation: bool,
    pub refresh_conversation: bool,
    pub mark_conversation_read: bool,
    pub load_conversation_history: bool,
    pub navigate_conversation_dates: bool,
    pub load_thread: bool,
    pub mark_thread_read: bool,
    pub send_thread_reply: bool,
    pub search_messages: bool,
    pub search_quick_switch: bool,
    pub load_workspace: bool,
    pub load_cached_workspace: bool,
    pub send_message: bool,
    pub mutate_drafts: bool,
    pub schedule_message: bool,
    pub delete_scheduled_message: bool,
    pub forward_message: bool,
    pub mutate_reactions: bool,
    pub load_message_permalink: bool,
    pub update_message: bool,
    pub delete_message: bool,
    pub mutate_message_saved_state: bool,
    pub mutate_stars: bool,
    pub load_channel_permalink: bool,
    pub upload_files: bool,
    pub stage_file: bool,
    pub cancel_file_staging: bool,
    pub reconcile_file_staging: bool,
    pub cleanup_staged_file: bool,
    pub share_files: bool,
    pub load_profile: bool,
    pub load_remote_image: bool,
    pub prepare_attachment_media: bool,
}
