mod list_state;
mod workspace_views;

#[cfg(test)]
use super::super::SlackMediaState;
use super::super::{
    AppearanceMode, Arc, ChatStartup, Date, Entity, HashMap, HashSet, PreparedSlackChannelDetails,
    RefCell, ScrollHandle, SlackActivationLoadProfile, SlackActiveMainComposerContext,
    SlackActiveScheduledEdit, SlackAttachmentSelection, SlackAuxPanelState,
    SlackBookmarkFolderIdentity, SlackBookmarkFolderRow, SlackChannelCreatorLoadKey,
    SlackChannelCreatorLoadRequest, SlackChannelDetailsLoadRequest, SlackChannelMenuSubmenu,
    SlackChannelNotificationLoadRequest, SlackChannelNotificationMutationRequest,
    SlackChannelPermalinkRequest, SlackChannelStarRequest, SlackComposerCaptureCoordinator,
    SlackComposerDocument, SlackComposerDraft, SlackComposerDraftKey, SlackComposerFiles,
    SlackComposerFormatAction, SlackComposerIdAllocator, SlackComposerLinkDialog,
    SlackComposerScheduleRecovery, SlackComposerTarget, SlackConversationHistoryRequest,
    SlackConversationLiveTarget, SlackConversationLoadProfile, SlackConversationLoadRoute,
    SlackConversationReadOverlay, SlackConversationReadRequest, SlackConversationReadState,
    SlackConversationRefreshRequest, SlackConversationTabsCache, SlackDateJumpOverlay,
    SlackDateJumpRequest, SlackDraftDesiredState, SlackDraftMutationState, SlackDraftRestore,
    SlackDraftSyncIdentity, SlackDraftSyncState, SlackExternalMembersSummary,
    SlackExternalOrganizationBadge, SlackFileStagingCoordinator, SlackFilesFilter,
    SlackHeaderControl, SlackHistoryDestination, SlackHistoryEntry, SlackMainRoute, SlackMainTab,
    SlackMediaPlayback, SlackMediaReconciliationKey, SlackMemberRow, SlackMembersLoad,
    SlackMentionPickerState, SlackMessageActionTarget, SlackMessageChunk, SlackMessageClientId,
    SlackMessageDeleteModal, SlackMessageDeleteRequest, SlackMessageEditRequest,
    SlackMessageForwardModal, SlackMessageMarkUnreadRequest, SlackMessageMenuState,
    SlackMessageNavigationHighlight, SlackMessageNavigationRequest, SlackMessagePermalinkRequest,
    SlackMessageRow, SlackMessageSavedRequest, SlackMoreView, SlackNewMessageCandidateRow,
    SlackNewMessageDestination, SlackNewMessageDraftKey, SlackNewMessageOpenLoad,
    SlackNewMessagePerson, SlackOutboundDelivery, SlackPendingThreadReplySend, SlackPinRow,
    SlackPinsLoadRequest, SlackProfilePanelState, SlackQuickSearchMessageRow, SlackQuickSearchRow,
    SlackRailMenu, SlackRailView, SlackReactionCatalogLoad, SlackReactionPickerCatalog,
    SlackReactionPickerState, SlackReactionRequest, SlackRemoteDraftFileCoordinator,
    SlackRemoteDraftState, SlackRemoteImageCache, SlackScheduleOverlayState,
    SlackSchedulePendingSubmission, SlackScheduledDeleteIdentity, SlackScheduledEditRecovery,
    SlackSearchRow, SlackSendRequest, SlackSkinToneLoadRequest, SlackSkinToneMutationRequest,
    SlackThreadPanelState, SlackThreadReadRequest, SlackThreadReadState, SlackVideoClipModal,
    SlackWorkspaceApiCapabilities, SurfaceTheme, WorkspaceApi,
};
pub(crate) use list_state::SlackListState;
use std::ops::{Deref, DerefMut};
use workspace_views::SlackWorkspaceViewsData;

#[derive(Default)]
pub struct SurfaceStateData {
    pub(crate) theme: SurfaceTheme,
    pub(crate) active: bool,
    pub(crate) appearance_mode: AppearanceMode,
    pub(crate) preview_width: f32,
    pub(crate) viewport_height: f32,
    pub(crate) slack_sidebar_preferred_ratio: f32,
    pub(crate) legacy_slack_sidebar_width: Option<f32>,
    pub(crate) slack_workspace_switcher_expanded: bool,
    pub(crate) embedded_shell: bool,
    pub(crate) slack_shell: Option<crate::ui::SlackWorkspaceShell>,
    pub(crate) slack_shell_snapshot: Option<crate::ui::SlackShellSnapshot>,
    pub(crate) slack_sidebar_snapshot: Option<crate::ui::SlackSidebarSnapshot>,
    pub(crate) slack_dm_inbox_snapshot: Option<crate::ui::SlackDmInboxSnapshot>,
    pub(crate) slack_conversation_snapshot: Option<crate::ui::SlackConversationSnapshot>,
    pub(crate) slack_workspace: Option<Arc<crate::ui::SlackWorkspace>>,
    pub(crate) workspace_api: Option<Arc<dyn WorkspaceApi>>,
    pub(crate) local_file_api: Option<Arc<dyn crate::model::SlackLocalFileApi>>,
    pub(crate) slack_workspace_api_capabilities: SlackWorkspaceApiCapabilities,
    pub(crate) chat_startup: ChatStartup,
    pub(crate) media_capture_api: Option<Arc<crate::ui::MediaCaptureApi>>,
    workspace_views: SlackWorkspaceViewsData,
    pub(crate) slack_pending_draft_restore: Option<SlackDraftRestore>,
    pub(crate) slack_scheduled_mutation_generation: u64,
    pub(crate) slack_scheduled_delete_pending: Option<SlackScheduledDeleteIdentity>,
    pub(crate) slack_main_route: SlackMainRoute,
    pub(crate) slack_directory_team_id: Option<String>,
    pub(crate) slack_directory_snapshot: Option<crate::ui::SlackDestinationDirectorySnapshot>,
    pub(crate) slack_directory_rows: Arc<[SlackNewMessageCandidateRow]>,
    pub(crate) slack_directory_visible_row_indices: Arc<[usize]>,
    pub(crate) slack_directory_scroll_handle: gpui::UniformListScrollHandle,
    pub(crate) slack_directory_query: String,
    pub(crate) slack_directory_normalized_query: gpui::SharedString,
    pub(crate) slack_directory_selected_index: Option<usize>,
    pub(crate) slack_directory_prefetched_range: Option<(usize, usize)>,
    pub(crate) slack_directory_generation: u64,
    pub(crate) slack_directory_loading: bool,
    pub(crate) slack_directory_error: Option<String>,
    pub(crate) slack_directory_focus_pending: bool,
    pub(crate) slack_new_message_team_id: Option<String>,
    pub(crate) slack_new_message_directory_snapshot:
        Option<crate::ui::SlackDestinationDirectorySnapshot>,
    pub(crate) slack_new_message_rows: Arc<[SlackNewMessageCandidateRow]>,
    pub(crate) slack_new_message_visible_row_indices: Arc<[usize]>,
    pub(crate) slack_new_message_scroll_handle: gpui::UniformListScrollHandle,
    pub(crate) slack_new_message_query: String,
    pub(crate) slack_new_message_normalized_query: gpui::SharedString,
    pub(crate) slack_new_message_to_focused: bool,
    pub(crate) slack_new_message_selected_index: Option<usize>,
    pub(crate) slack_new_message_selected_people: Vec<SlackNewMessagePerson>,
    pub(crate) slack_new_message_destination: Option<SlackNewMessageDestination>,
    pub(crate) slack_new_message_active_draft_key: Option<String>,
    pub(crate) slack_new_message_drafts: HashMap<SlackNewMessageDraftKey, SlackComposerDraft>,
    pub(crate) slack_new_message_return_draft: Option<(SlackComposerDraftKey, SlackComposerDraft)>,
    pub(crate) slack_new_message_prefetched_range: Option<(usize, usize)>,
    pub(crate) slack_new_message_directory_generation: u64,
    pub(crate) slack_new_message_directory_loading: bool,
    pub(crate) slack_new_message_open_generation: u64,
    pub(crate) slack_new_message_open_request: Option<SlackNewMessageOpenLoad>,
    pub(crate) slack_new_message_pending_open: Option<SlackNewMessageOpenLoad>,
    pub(crate) slack_new_message_error: Option<String>,
    pub(crate) slack_slackbot_opening: bool,
    pub(crate) slack_pins_snapshot: Option<crate::ui::SlackPinsSnapshot>,
    pub(crate) slack_pins_rows: Arc<[SlackPinRow]>,
    pub(crate) slack_pins_list_state: SlackListState,
    pub(crate) slack_pins_generation: u64,
    pub(crate) slack_pins_inflight: HashMap<(String, String), u64>,
    pub(crate) slack_pins_request: Option<SlackPinsLoadRequest>,
    pub(crate) slack_pins_loading: bool,
    pub(crate) slack_pins_error: Option<String>,
    pub(crate) slack_active_bookmark_folder: Option<SlackBookmarkFolderIdentity>,
    pub(crate) slack_active_bookmark_folder_label: Option<gpui::SharedString>,
    pub(crate) slack_bookmark_folder_rows: Arc<[SlackBookmarkFolderRow]>,
    pub(crate) slack_bookmark_folder_scroll_handle: gpui::UniformListScrollHandle,
    pub(crate) slack_bookmark_folder_generation: u64,
    pub(crate) slack_bookmark_folder_loading: bool,
    pub(crate) slack_bookmark_folder_error: Option<gpui::SharedString>,
    pub(crate) slack_members_conversation_id: Option<String>,
    pub(crate) slack_members_deferred_conversation_id: Option<String>,
    pub(crate) slack_members_snapshot: Option<crate::ui::SlackConversationMembersSnapshot>,
    pub(crate) slack_external_members_summary: Option<SlackExternalMembersSummary>,
    pub(crate) slack_external_organization_badges_by_user_id:
        HashMap<String, SlackExternalOrganizationBadge>,
    pub(crate) slack_members_rows: Arc<[SlackMemberRow]>,
    pub(crate) slack_members_visible_row_indices: Arc<[usize]>,
    pub(crate) slack_members_scroll_handle: gpui::UniformListScrollHandle,
    pub(crate) slack_members_query: String,
    pub(crate) slack_members_generation: u64,
    pub(crate) slack_members_request: Option<SlackMembersLoad>,
    pub(crate) slack_members_loading: bool,
    pub(crate) slack_members_error: Option<String>,
    pub(crate) slack_members_panel_open: bool,
    pub(crate) slack_members_focus_pending: bool,
    pub(crate) slack_members_prefetched_range: Option<(usize, usize)>,
    pub(crate) slack_search_open: bool,
    pub(crate) slack_search_results_open: bool,
    pub(crate) slack_search_query: String,
    pub(crate) slack_search_request_query: String,
    pub(crate) slack_search_committed_query: String,
    pub(crate) slack_search_options: crate::ui::SlackMessageSearchOptions,
    pub(crate) slack_search_scope_modifier: Option<String>,
    pub(crate) slack_search_selected_option: usize,
    pub(crate) slack_search_generation: u64,
    pub(crate) slack_quick_search_rows: Arc<[SlackQuickSearchRow]>,
    pub(crate) slack_quick_search_message_rows: Arc<[SlackQuickSearchMessageRow]>,
    pub(crate) slack_quick_search_options_scroll_handle: ScrollHandle,
    pub(crate) slack_quick_search_scroll_handle: gpui::UniformListScrollHandle,
    pub(crate) slack_quick_search_prefetched_range: Option<(usize, usize)>,
    pub(crate) slack_quick_search_loading: bool,
    pub(crate) slack_quick_search_error: Option<gpui::SharedString>,
    pub(crate) slack_quick_message_last_started_at: Option<std::time::Instant>,
    pub(crate) slack_search_rows: Arc<[SlackSearchRow]>,
    pub(crate) slack_search_list_state: SlackListState,
    pub(crate) slack_search_total: u32,
    pub(crate) slack_search_next_cursor: Option<String>,
    pub(crate) slack_search_loading: bool,
    pub(crate) slack_search_error: Option<String>,
    pub(crate) slack_message_chunks: Arc<[SlackMessageChunk]>,
    pub(crate) slack_message_rows: Arc<[SlackMessageRow]>,
    pub(crate) slack_message_rows_local_today: Option<Date>,
    pub(crate) slack_message_list_state: SlackListState,
    pub(crate) slack_message_list_auto_position_active: bool,
    pub(crate) slack_new_message_count: usize,
    pub(crate) slack_message_history_generation: u64,
    pub(crate) slack_message_history_request: Option<SlackConversationHistoryRequest>,
    pub(crate) slack_message_navigation_generation: u64,
    pub(crate) slack_message_navigation: Option<SlackMessageNavigationRequest>,
    pub(crate) slack_message_navigation_highlight: Option<SlackMessageNavigationHighlight>,
    pub(crate) slack_message_navigation_focus_pending: bool,
    pub(crate) slack_conversation_revision: u64,
    pub(crate) slack_conversation_live_target: Option<SlackConversationLiveTarget>,
    pub(crate) slack_conversation_live_generation: u64,
    pub(crate) slack_conversation_refresh_timer_generation: Option<u64>,
    pub(crate) slack_conversation_refresh_timer_serial: u64,
    pub(crate) slack_conversation_refresh_request: Option<SlackConversationRefreshRequest>,
    pub(crate) slack_conversation_reconciliation_target: Option<SlackConversationLiveTarget>,
    pub(crate) slack_conversation_refresh_failures: u8,
    pub(crate) slack_conversation_read_pending: Option<SlackConversationReadRequest>,
    pub(crate) slack_conversation_read_timer: Option<SlackConversationReadRequest>,
    pub(crate) slack_conversation_read_request: Option<SlackConversationReadRequest>,
    pub(crate) slack_conversation_read_overlays:
        HashMap<SlackConversationLiveTarget, SlackConversationReadOverlay>,
    pub(crate) slack_sidebar_read_epoch: u64,
    pub(crate) slack_conversation_read_state: Option<SlackConversationReadState>,
    pub(crate) slack_conversation_read_failures: u8,
    pub(crate) slack_profile_scroll_handle: ScrollHandle,
    pub(crate) slack_composer_text: String,
    pub(crate) slack_active_main_composer_context: Option<SlackActiveMainComposerContext>,
    pub(crate) slack_composer_document: RefCell<SlackComposerDocument>,
    pub(crate) slack_composer_focused: bool,
    pub(crate) slack_composer_format_roving_target: SlackComposerFormatAction,
    pub(crate) slack_composer_link_dialog: Option<SlackComposerLinkDialog>,
    pub(crate) slack_composer_link_focus_pending: bool,
    pub(crate) slack_error: Option<String>,
    pub(crate) slack_composer_drafts: HashMap<SlackComposerDraftKey, SlackComposerDraft>,
    pub(crate) slack_remote_drafts: HashMap<SlackComposerDraftKey, SlackRemoteDraftState>,
    pub(crate) slack_draft_desired_states: HashMap<SlackComposerDraftKey, SlackDraftDesiredState>,
    pub(crate) slack_draft_mutation_states: HashMap<SlackComposerDraftKey, SlackDraftMutationState>,
    pub(crate) slack_draft_mutation_errors: HashMap<SlackComposerDraftKey, String>,
    pub(crate) slack_draft_mutation_serial: u64,
    pub(crate) slack_draft_sync_identity: Option<SlackDraftSyncIdentity>,
    pub(crate) slack_draft_sync_generation: u64,
    pub(crate) slack_draft_sync_state: SlackDraftSyncState,
    pub(crate) slack_composer_ids: SlackComposerIdAllocator,
    pub(crate) slack_composer_files: SlackComposerFiles,
    pub(crate) slack_composer_capture: SlackComposerCaptureCoordinator,
    pub(crate) slack_video_clip_modal: Option<Entity<SlackVideoClipModal>>,
    pub(crate) slack_file_staging: SlackFileStagingCoordinator,
    pub(crate) slack_remote_draft_files: SlackRemoteDraftFileCoordinator,
    pub(crate) slack_send_generation: u64,
    pub(crate) slack_send_draft_revision: u64,
    pub(crate) slack_send_draft_token_generation: u64,
    pub(crate) slack_send_draft_token: u64,
    pub(crate) slack_send_client_message_id: Option<SlackMessageClientId>,
    pub(crate) slack_pending_sends: HashMap<u64, SlackSendRequest>,
    pub(crate) slack_outbound_delivery_ledger: Vec<SlackOutboundDelivery>,
    pub(crate) slack_local_delivery_rows: Arc<[SlackMessageRow]>,
    pub(crate) slack_schedule_overlay: Option<SlackScheduleOverlayState>,
    pub(crate) slack_schedule_generation: u64,
    pub(crate) slack_schedule_pending: Option<SlackSchedulePendingSubmission>,
    pub(crate) slack_composer_schedule_recovery: Option<SlackComposerScheduleRecovery>,
    pub(crate) slack_schedule_submission_error: Option<String>,
    pub(crate) slack_active_scheduled_edit: Option<SlackActiveScheduledEdit>,
    pub(crate) slack_scheduled_edit_recovery: Option<SlackScheduledEditRecovery>,
    pub(crate) slack_reaction_generation: u64,
    pub(crate) slack_pending_reactions:
        HashMap<Arc<SlackMessageActionTarget>, SlackReactionRequest>,
    pub(crate) slack_reaction_catalog_generation: u64,
    pub(crate) slack_reaction_catalog_request: Option<SlackReactionCatalogLoad>,
    pub(crate) slack_reaction_catalog_error: Option<gpui::SharedString>,
    pub(crate) slack_reaction_picker_catalog: SlackReactionPickerCatalog,
    pub(crate) slack_reaction_picker: Option<SlackReactionPickerState>,
    pub(crate) slack_reaction_picker_focus_pending: bool,
    pub(crate) slack_skin_tone_team_id: Option<String>,
    pub(crate) slack_preferred_skin_tone: Option<crate::ui::SlackPreferredSkinTone>,
    pub(crate) slack_skin_tone_generation: u64,
    pub(crate) slack_skin_tone_load_request: Option<SlackSkinToneLoadRequest>,
    pub(crate) slack_skin_tone_mutation_request: Option<SlackSkinToneMutationRequest>,
    pub(crate) slack_skin_tone_error: Option<gpui::SharedString>,
    pub(crate) slack_skin_tone_menu_open: bool,
    pub(crate) slack_skin_tone_menu_selected: Option<crate::ui::SlackSkinTone>,
    pub(crate) slack_skin_tone_menu_focus_pending: bool,
    pub(crate) slack_message_menu: Option<SlackMessageMenuState>,
    pub(crate) slack_message_menu_focus_pending: bool,
    pub(crate) slack_date_jump_overlay: Option<SlackDateJumpOverlay>,
    pub(crate) slack_date_jump_generation: u64,
    pub(crate) slack_date_jump_request: Option<SlackDateJumpRequest>,
    pub(crate) slack_message_saved_generation: u64,
    pub(crate) slack_pending_message_saved: Option<SlackMessageSavedRequest>,
    pub(crate) slack_message_permalink_generation: u64,
    pub(crate) slack_pending_message_permalink: Option<SlackMessagePermalinkRequest>,
    pub(crate) slack_message_forward_modal: Option<SlackMessageForwardModal>,
    pub(crate) slack_message_forward_generation: u64,
    pub(crate) slack_message_forward_focus_pending: bool,
    pub(crate) slack_message_forward_note_focus_pending: bool,
    pub(crate) slack_message_edit_generation: u64,
    pub(crate) slack_pending_message_edit: Option<SlackMessageEditRequest>,
    pub(crate) slack_message_delete_modal: Option<SlackMessageDeleteModal>,
    pub(crate) slack_message_delete_generation: u64,
    pub(crate) slack_pending_message_delete: Option<SlackMessageDeleteRequest>,
    pub(crate) slack_message_mark_unread_generation: u64,
    pub(crate) slack_pending_message_mark_unread: Option<SlackMessageMarkUnreadRequest>,
    pub(crate) slack_aux_panel: Option<SlackAuxPanelState>,
    pub(crate) slack_composer_aux_target: Option<SlackComposerTarget>,
    pub(crate) slack_mention_picker_state: Option<SlackMentionPickerState>,
    pub(crate) slack_pending_conversation_id: Option<String>,
    pub(crate) slack_pending_conversation_route: SlackConversationLoadRoute,
    pub(crate) slack_active_loading_conversation_ids: HashSet<String>,
    pub(crate) slack_activation_load_profile: Option<SlackActivationLoadProfile>,
    pub(crate) slack_conversation_load_profile: Option<SlackConversationLoadProfile>,
    pub(crate) slack_profile_panel: Option<SlackProfilePanelState>,
    pub(crate) slack_self_menu_open: bool,
    pub(crate) slack_self_status_dialog: Option<crate::ui::surface::SlackSelfStatusDialog>,
    pub(crate) slack_self_status: Option<crate::ui::SlackSelfStatus>,
    pub(crate) slack_self_settings_generation: u64,
    pub(crate) slack_self_presence_mutating: bool,
    pub(crate) slack_self_settings_error: Option<String>,
    pub(crate) slack_sidebar_section_dialog: Option<crate::ui::surface::SlackSidebarSectionDialog>,
    pub(crate) slack_sidebar_section_generation: u64,
    pub(crate) slack_thread_panel: Option<SlackThreadPanelState>,
    pub(crate) slack_thread_generation: u64,
    pub(crate) slack_thread_read_pending: Option<SlackThreadReadRequest>,
    pub(crate) slack_thread_read_timer: Option<SlackThreadReadRequest>,
    pub(crate) slack_thread_read_request: Option<SlackThreadReadRequest>,
    pub(crate) slack_thread_read_state: Option<SlackThreadReadState>,
    pub(crate) slack_thread_read_failures: u8,
    pub(crate) slack_thread_read_window_active: bool,
    pub(crate) slack_thread_reply_generation: u64,
    pub(crate) slack_pending_thread_replies:
        HashMap<SlackComposerDraftKey, SlackPendingThreadReplySend>,
    pub(crate) slack_active_rail_view: SlackRailView,
    pub(crate) slack_upgrade_card_dismissed: bool,
    pub(crate) slack_rail_menu: Option<SlackRailMenu>,
    pub(crate) slack_more_view: SlackMoreView,
    pub(crate) slack_hidden_rail_views: HashSet<SlackRailView>,
    pub(crate) slack_dms_peek_visible: bool,
    pub(crate) slack_active_tab: SlackMainTab,
    pub(crate) slack_conversation_tabs_cache: SlackConversationTabsCache,
    pub(crate) slack_conversation_tab_roving_key: gpui::SharedString,
    pub(crate) slack_conversation_tabs_overflow_open: bool,
    pub(crate) slack_conversation_tabs_overflow_selected_index: Option<usize>,
    pub(crate) slack_conversation_tabs_overflow_focus_pending: bool,
    pub(crate) slack_dms_show_unread_only: bool,
    pub(crate) slack_files_filter: SlackFilesFilter,
    pub(crate) slack_muted_conversations: HashSet<String>,
    pub(crate) slack_collapsed_sections: HashSet<String>,
    pub(crate) slack_formatting_enabled: bool,
    pub(crate) slack_expanded_attachment: Option<SlackAttachmentSelection>,
    pub(crate) slack_collapsed_attachment_ids: HashSet<String>,
    pub(crate) slack_remote_images: SlackRemoteImageCache,
    pub(crate) slack_active_remote_image_urls: HashSet<String>,
    pub(crate) slack_pending_remote_image_urls: Vec<String>,
    pub(crate) slack_remote_image_queue_dirty: bool,
    #[cfg(test)]
    pub(crate) slack_media_states: HashMap<String, SlackMediaState>,
    pub(crate) slack_media_playback_generation: u64,
    pub(crate) slack_media_playback: Option<SlackMediaPlayback>,
    pub(crate) slack_media_reconciled_key: Option<SlackMediaReconciliationKey>,
    pub(crate) slack_conversation_history: Vec<SlackHistoryEntry>,
    pub(crate) slack_conversation_history_index: usize,
    pub(crate) slack_history_target_index: Option<usize>,
    pub(crate) slack_history_menu_target: Option<SlackHistoryDestination>,
    pub(crate) slack_history_menu_open: bool,
    pub(crate) slack_history_menu_selected_index: Option<usize>,
    pub(crate) slack_header_roving_target: SlackHeaderControl,
    pub(crate) slack_channel_move_menu_open: bool,
    pub(crate) slack_channel_move_menu_focus_pending: bool,
    pub(crate) slack_header_move_focus_pending: bool,
    pub(crate) slack_channel_notification_preference:
        Option<crate::ui::SlackChannelNotificationPreference>,
    pub(crate) slack_channel_notification_generation: u64,
    pub(crate) slack_channel_notification_load_request: Option<SlackChannelNotificationLoadRequest>,
    pub(crate) slack_channel_notification_mutation_request:
        Option<SlackChannelNotificationMutationRequest>,
    pub(crate) slack_channel_notification_loading: bool,
    pub(crate) slack_channel_notification_error: Option<gpui::SharedString>,
    pub(crate) slack_channel_notifications_menu_open: bool,
    pub(crate) slack_channel_notifications_advanced_open: bool,
    pub(crate) slack_channel_notifications_menu_selected_index: usize,
    pub(crate) slack_channel_notifications_menu_keyboard_highlighted: bool,
    pub(crate) slack_channel_notifications_menu_focus_pending: bool,
    pub(crate) slack_header_notifications_focus_pending: bool,
    pub(crate) slack_channel_menu_open: bool,
    pub(crate) slack_channel_menu_focus_pending: bool,
    pub(crate) slack_channel_submenu_focus_pending: bool,
    pub(crate) slack_channel_menu_selected_index: Option<usize>,
    pub(crate) slack_channel_menu_submenu: Option<SlackChannelMenuSubmenu>,
    pub(crate) slack_channel_submenu_selected_index: Option<usize>,
    pub(crate) slack_channel_details_open: bool,
    pub(crate) slack_channel_details_cache: HashMap<(String, String), PreparedSlackChannelDetails>,
    pub(crate) slack_channel_details: Option<PreparedSlackChannelDetails>,
    pub(crate) slack_channel_details_generation: u64,
    pub(crate) slack_channel_details_inflight: HashMap<(String, String), u64>,
    pub(crate) slack_channel_details_request: Option<SlackChannelDetailsLoadRequest>,
    pub(crate) slack_channel_details_loading: bool,
    pub(crate) slack_channel_details_error: Option<gpui::SharedString>,
    pub(crate) slack_channel_creator_generation: u64,
    pub(crate) slack_channel_creator_inflight: HashMap<SlackChannelCreatorLoadKey, u64>,
    pub(crate) slack_channel_creator_request: Option<SlackChannelCreatorLoadRequest>,
    pub(crate) slack_channel_star_generation: u64,
    pub(crate) slack_pending_channel_star: Option<SlackChannelStarRequest>,
    pub(crate) slack_channel_permalink_generation: u64,
    pub(crate) slack_pending_channel_permalink: Option<SlackChannelPermalinkRequest>,
    #[cfg(test)]
    pub(crate) slack_test_conversation_starred: bool,
    #[cfg(test)]
    pub(crate) slack_test_channel_details_visible: bool,
    #[cfg(test)]
    pub(crate) slack_test_conversation_muted: bool,
    #[cfg(test)]
    pub(crate) slack_test_huddle_active: bool,
}

impl Deref for SurfaceStateData {
    type Target = SlackWorkspaceViewsData;

    fn deref(&self) -> &Self::Target {
        &self.workspace_views
    }
}

impl DerefMut for SurfaceStateData {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.workspace_views
    }
}
