use super::AppearanceMode;

#[derive(Clone, Copy)]
pub(crate) struct SlackPalette {
    pub(crate) surface_bg: u32,
    pub(crate) surface_text: u32,
    pub(crate) sidebar_bg: u32,
    pub(crate) sidebar_border: u32,
    pub(crate) sidebar_header_text: u32,
    pub(crate) sidebar_icon: u32,
    pub(crate) sidebar_text: u32,
    pub(crate) sidebar_unread_text: u32,
    pub(crate) sidebar_muted_text: u32,
    pub(crate) sidebar_section_text: u32,
    pub(crate) sidebar_section_icon: u32,
    pub(crate) sidebar_active_bg: u32,
    pub(crate) sidebar_active_text: u32,
    pub(crate) sidebar_badge_bg: u32,
    pub(crate) sidebar_badge_text: u32,
    pub(crate) sidebar_more_unreads_bg: u32,
    pub(crate) sidebar_more_unreads_hover_bg: u32,
    pub(crate) sidebar_more_unreads_text: u32,
    pub(crate) main_bg: u32,
    pub(crate) main_text: u32,
    pub(crate) main_secondary_text: u32,
    pub(crate) main_muted_text: u32,
    pub(crate) main_border: u32,
    pub(crate) reaction_picker_border: u32,
    pub(crate) reaction_picker_footer_bg: u32,
    pub(crate) reaction_picker_hover_bg: u32,
    pub(crate) reaction_picker_focus_bg: u32,
    pub(crate) reaction_picker_focus_border: u32,
    pub(crate) topic_bg: u32,
    pub(crate) composer_bg: u32,
    pub(crate) composer_border: u32,
    pub(crate) composer_focused_border: u32,
    pub(crate) composer_placeholder: u32,
    pub(crate) composer_icon: u32,
    pub(crate) composer_icon_bg: u32,
    pub(crate) composer_chip_bg: u32,
    pub(crate) composer_chip_border: u32,
    pub(crate) composer_chip_text: u32,
    pub(crate) send_disabled_icon: u32,
    pub(crate) send_disabled_border: u32,
    pub(crate) message_author: u32,
    pub(crate) date_divider_text: u32,
    pub(crate) link: u32,
    pub(crate) attachment_border: u32,
    pub(crate) attachment_bg: u32,
    pub(crate) attachment_text: u32,
    pub(crate) attachment_muted_text: u32,
}

#[derive(Clone, Copy)]
pub(crate) struct SlackActivityPalette {
    pub(crate) surface_bg: u32,
    pub(crate) card_bg: u32,
    pub(crate) unread_card_bg: u32,
    pub(crate) primary_text: u32,
    pub(crate) secondary_text: u32,
    pub(crate) tertiary_text: u32,
    pub(crate) card_border: u32,
    pub(crate) card_border_alpha: f32,
    pub(crate) card_hover_border_alpha: f32,
    pub(crate) focus_border: u32,
    pub(crate) selected_ring: u32,
    pub(crate) importance_bg: u32,
    pub(crate) importance_text: u32,
    pub(crate) error_text: u32,
    pub(crate) interaction_hover: u32,
    pub(crate) interaction_hover_alpha: f32,
    pub(crate) action_hover: u32,
    pub(crate) action_hover_alpha: f32,
    pub(crate) reaction_hover_border: u32,
    pub(crate) avatar_backing_alpha: f32,
}

pub(crate) fn slack_palette(appearance_mode: AppearanceMode) -> SlackPalette {
    match appearance_mode {
        AppearanceMode::Dark => dark_slack_palette(),
        AppearanceMode::Light => light_slack_palette(),
    }
}

pub(crate) fn slack_activity_palette(appearance_mode: AppearanceMode) -> SlackActivityPalette {
    match appearance_mode {
        AppearanceMode::Dark => SlackActivityPalette {
            surface_bg: 0x1a1d21,
            card_bg: 0x1a1d21,
            unread_card_bg: 0x212428,
            primary_text: 0xf8f8f8,
            secondary_text: 0xb9babd,
            tertiary_text: 0x9a9b9e,
            card_border: 0x797c81,
            card_border_alpha: 77.0 / 255.0,
            card_hover_border_alpha: 128.0 / 255.0,
            focus_border: 0x2ba5ce,
            selected_ring: 0xf8f8f8,
            importance_bg: 0xef3e75,
            importance_text: 0xfff4f4,
            error_text: 0xde678a,
            interaction_hover: 0xf8f8f8,
            interaction_hover_alpha: 20.0 / 255.0,
            action_hover: 0xe8e8e8,
            action_hover_alpha: 0.04,
            reaction_hover_border: 0x797c81,
            avatar_backing_alpha: 0.13,
        },
        AppearanceMode::Light => SlackActivityPalette {
            surface_bg: 0xffffff,
            card_bg: 0xf8f8f8,
            unread_card_bg: 0xffffff,
            primary_text: 0x1d1c1d,
            secondary_text: 0x454447,
            tertiary_text: 0x5e5d60,
            card_border: 0x5e5d60,
            card_border_alpha: 33.0 / 255.0,
            card_hover_border_alpha: 115.0 / 255.0,
            focus_border: 0x1264a3,
            selected_ring: 0xf8f8f8,
            importance_bg: 0xef3e75,
            importance_text: 0xfff4f4,
            error_text: 0xc01343,
            interaction_hover: 0x454447,
            interaction_hover_alpha: 15.0 / 255.0,
            action_hover: 0x1d1c1d,
            action_hover_alpha: 0.04,
            reaction_hover_border: 0x7c7a7f,
            avatar_backing_alpha: 0.13,
        },
    }
}

fn dark_slack_palette() -> SlackPalette {
    SlackPalette {
        surface_bg: 0x0d0d0d,
        surface_text: 0xd1d2d3,
        sidebar_bg: 0x0f1011,
        sidebar_border: 0x2f2f31,
        sidebar_header_text: 0xf8f8f8,
        sidebar_icon: 0xbababa,
        sidebar_text: 0xbababa,
        sidebar_unread_text: 0xf8f8f8,
        sidebar_muted_text: 0x909091,
        sidebar_section_text: 0xbababa,
        sidebar_section_icon: 0xbababa,
        sidebar_active_bg: 0xf8f8f8,
        sidebar_active_text: 0x0c0f0f,
        sidebar_badge_bg: 0xef3e75,
        sidebar_badge_text: 0xfff4f4,
        sidebar_more_unreads_bg: 0x2e2e2e,
        sidebar_more_unreads_hover_bg: 0x3e3e3e,
        sidebar_more_unreads_text: 0xf8f8f8,
        main_bg: 0x1b1d21,
        main_text: 0xd1d2d3,
        main_secondary_text: 0xb9babd,
        main_muted_text: 0x9ca2a9,
        main_border: 0x242629,
        reaction_picker_border: 0x3f4147,
        reaction_picker_footer_bg: 0x232529,
        reaction_picker_hover_bg: 0x2d3034,
        reaction_picker_focus_bg: 0x1d3c4a,
        reaction_picker_focus_border: 0x1d9bd1,
        topic_bg: 0x171a1d,
        composer_bg: 0x232529,
        composer_border: 0x575856,
        composer_focused_border: 0x575856,
        composer_placeholder: 0x9a9b9e,
        composer_icon: 0xb9babd,
        composer_icon_bg: 0xe8e8e8,
        composer_chip_bg: 0x2a2d31,
        composer_chip_border: 0x3a3f45,
        composer_chip_text: 0xe2e4e7,
        send_disabled_icon: 0xd1d2d3,
        send_disabled_border: 0xffffff,
        message_author: 0xf8f8f8,
        date_divider_text: 0xd4d7db,
        link: 0x33b7f3,
        attachment_border: 0x393d42,
        attachment_bg: 0x191c20,
        attachment_text: 0xe5e7ea,
        attachment_muted_text: 0x8c949d,
    }
}

fn light_slack_palette() -> SlackPalette {
    SlackPalette {
        surface_bg: 0x0d0d0d,
        surface_text: 0x1d1c1d,
        sidebar_bg: 0xe7e7e7,
        sidebar_border: 0xd9d9d9,
        sidebar_header_text: 0x1d1c1d,
        sidebar_icon: 0x5e5d60,
        sidebar_text: 0x454447,
        sidebar_unread_text: 0x1d1c1d,
        sidebar_muted_text: 0x69686b,
        sidebar_section_text: 0x69686b,
        sidebar_section_icon: 0x69686b,
        sidebar_active_bg: 0xf8f8f8,
        sidebar_active_text: 0x1d1c1d,
        sidebar_badge_bg: 0xe01e5a,
        sidebar_badge_text: 0xffffff,
        sidebar_more_unreads_bg: 0xf6f6f6,
        sidebar_more_unreads_hover_bg: 0xe8e8e8,
        sidebar_more_unreads_text: 0x0e0e0e,
        main_bg: 0xffffff,
        main_text: 0x1d1c1d,
        main_secondary_text: 0x5e5d60,
        main_muted_text: 0x696969,
        main_border: 0xdddddd,
        reaction_picker_border: 0xdddddd,
        reaction_picker_footer_bg: 0xf8f8f8,
        reaction_picker_hover_bg: 0xf4f4f4,
        reaction_picker_focus_bg: 0xe8f5fa,
        reaction_picker_focus_border: 0x1264a3,
        topic_bg: 0xf8f8f8,
        composer_bg: 0xffffff,
        composer_border: 0xb8b8b8,
        composer_focused_border: 0x1264a3,
        composer_placeholder: 0x5e5d60,
        composer_icon: 0x5e5d60,
        composer_icon_bg: 0x1d1c1d,
        composer_chip_bg: 0xf6f6f6,
        composer_chip_border: 0xd7d7d7,
        composer_chip_text: 0x1d1c1d,
        send_disabled_icon: 0xb8b8b8,
        send_disabled_border: 0x000000,
        message_author: 0x1d1c1d,
        date_divider_text: 0x1d1c1d,
        link: 0x1264a3,
        attachment_border: 0xd0d0d0,
        attachment_bg: 0xffffff,
        attachment_text: 0x1d1c1d,
        attachment_muted_text: 0x696969,
    }
}
